apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 3
  template:
    metadata:
      name: node
      labels:
        app: node
    spec:
      containers:
      - image: k8schandra/node:v1
        name: nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: node
spec:
  type: LoadBalancer
  selector:
    app: node
  ports:
  - port: 80
    targetPort: 8080
