apiVersion: v1
kind: Pod
metadata:
  name: node-liveness
spec:
  containers:
  - image: k8schandra/node-unhealthy
    name: node-unhealthy
    livenessProbe:
      httpGet:
        path: /
        port: 8080

