apiVersion: v1
kind: Pod
metadata:
  name: node-manual
  namespace: custom-namespace
spec:
  containers:
  - image: k8schandra/nodeapp:v1
    name: nodeapp
    ports:
    - containerPort: 8080
      protocol: TCP
