apiVersion: v1
kind: Pod
metadata:
  name: node-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: k8schandra/nodeapp:v1
    name: nodeapp
    ports:
    - containerPort: 8080
      protocol: TCP
