apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-rc
spec:
  replicas: 3
  selector:
    app: k8s-rc
  template:
    metadata:
      labels:
        app: k8s-rc
    spec:
      containers:
      - name: k8s-rc
        image: k8schandra/nodeapp:v1
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          exec:
            command:
            - ls
            - /var/ready

